name: -Developing Build and Push

on:
  push:
    branches:
      - "*"

jobs:
  docker_dev_build_push:
    if: "contains(github.event.head_commit.message, 'build_dev')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clear Space
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nerdylive/stableswarm:dev-${{ github.sha }}
          cache-from: type=registry,ref=nerdylive/stableswarm:buildcache-dev
          cache-to: type=registry,ref=nerdylive/stableswarm:buildcache-dev,mode=max
